### ISSUE TITLE
Missing  gettoken.c?

### ISSUE THREAD

**Issue by zhouxs1023** [EmeraldWolfram/PrattParser#26]
I see source,but can not find getToken() function,  if Missing  gettoken.c file?

**Comment by EmeraldWolfram** [comment]
Hi zhouxs1023, 
getToken() and peepToken() are mocked inside the test as I assume getToken() and peepToken() as a function provided by the Tokenizer. Function getToken() should return the first token and remove it from the serial token list. Whereas, peepToken() should return a pointer to the first token without removing it.
